name: main

on:   
  push: 
    branches: ["main"]
  workflow_dispatch: 

jobs:
  node: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: node version
        run: node --version
        
  build:
    needs: node
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        run: npm ci
      - name: Creating build
        run: npm run build
        
        
        
