name: main

on:   
  push: 
    branches: ["main"]
  workflow_dispatch: 

jobs:
  hello: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: node version
        run: node --version
